# ⚙️ FULL-STACK PRODUCTION HARD-DRIVE STORAGE PARAMS
spring.application.name=CryptoDatabaseApp

# Persistent Relational Data Schema Architecture File Mapping
spring.datasource.url=jdbc:h2:file:./data/hala_academy_db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=12345

# 🛠️ HIBERNATE SCHEMA AND TRANS-LOG AUDIT ENGINE CONFS
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable Web-Console Remote Control Panel Access Gates
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
